services:
  oracle:
    image: daxua/oracledb:19.3.0-ee-arm64
    container_name: oracledb
    ports:
      - '1521:1521'
      - '5500:5500'
    environment:
      ORACLE_SID: ORCLCDB
      ORACLE_PDB: ORCLPDB1
      ORACLE_PWD: my-super-secret-password
      ORACLE_CHARACTERSET: AL32UTF8
      INIT_SGA_SIZE: 3000
      INIT_PGA_SIZE: 1000
    volumes:
      - oracle-data:/opt/oracle/oradata

networks:
  default:
    name: oracle-net

volumes:
  oracle-data:
