services:
  kv_server:
    build: .
    container_name: kv_server
    ports:
      - '5000:5000'
      - '8000:8000'
    volumes:
      - kv_data:/opt/kv/kvroot

  kv_client:
    build: .
    container_name: kv_client
    volumes:
      - kv_data:/opt/kv/kvroot:ro
    command: /bin/bash
    depends_on:
      - kv_server

networks:
  default:
    name: kv_net

volumes:
  kv_data:
